builds:
  - id: piknik
    main: .
    binary: piknik
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - piknik
    image_templates:
      - piknik:latest
    skip_push: true
    dockerfile: Dockerfile.goreleaser
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
